name: work-cuda-dev

on:
  push:
    paths:
      - 'work-cuda.Dockerfile'
      - 'scripts/start.sh'

  workflow_dispatch:
#  pull_request:
#    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the latest Docker image
        run: |
          DOCKER_BUILDKIT=0 docker build . --file work-cuda.Dockerfile --tag work-cuda-dev
          docker image tag work-cuda-dev ${{ secrets.DOCKERHUB_USERNAME }}/work-cuda-dev:latest
          docker image tag work-cuda-dev ${{ secrets.DOCKERHUB_USERNAME }}/work-cuda-dev:cuda12.4-ubuntu22.04
          docker image tag work-cuda-dev ${{ secrets.DOCKERHUB_USERNAME }}/work-cuda-dev:cuda12.4-ubuntu22.04-${{ steps.commit.outputs.short }}
      - name: Push the latest Docker image
        run: docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/work-cuda-dev
